run:
  go: '1.19'

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - testpackage
    - varnamelen
    - ireturn
    - gofumpt
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - gosec
        - unparam
        - gochecknoglobals
