run:
  allow-parallel-runners: true
  go: '1.19'

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - testpackage
    - varnamelen
    - ireturn
    - gofumpt

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
    enable-all: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: ._test\.go
      linters:
        - gochecknoglobals
        - unparam
        - gosec
